[tool.poetry]
name = "pythonpe-blog"
version = "0.1.0"
description = ""
authors = ["Ider Delzo <soloidx@gmail.com>", "Jean-Pierre Chauvel <jean.pierre@chauvel.org>"]
license = "Apache License, Version 2.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
Sphinx = "^7.2.6"
ablog = "^0.11.6"
pydata-sphinx-theme = "^0.15.2"
myst-parser = {extras = ["linkify"], version = "^2.0.0"}
sphinxcontrib-youtube = "^1.4.1"
sphinx-sitemap = "^2.5.1"
sphinxext-opengraph = "^0.9.1"
matplotlib = "^3.8.4"


[tool.poetry.group.dev.dependencies]
isort = "^5.13.2"
black = "^24.3.0"

[tool.black]
line-length = 79

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
