---
name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Set Locale
        run: |
          sudo apt-get update && sudo apt-get install tzdata locales -y
          sudo locale-gen es_ES.UTF-8
          sudo localectl set-locale LANG="es_ES.UTF-8"
          export LANG="es_ES.UTF-8"
          export LANGUAGE="es_ES.UTF-8"
          sudo update-locale
          locale -a
          locale
          locale -c -k LC_NUMERIC
          localectl status

      - name: Install Dependencies
        run: |
          uv sync

      - name: Build Blog
        run: |
          uv run ablog build
